version: "3.7"
services:
  background-services:
    image: background-services
    container_name: background-services
    depends_on:
      rabbitmqt:
        condition: service_healthy
    restart: always
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile
  rabbitmqt:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9890:15672
    hostname: stats
    volumes:
      - ./.volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - type: bind
        source: ./rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
  mosquitto:
    image: eclipse-mosquitto:2.0.14
    hostname: mosquitto
    volumes:
      - ./.services/mosquitto:/mosquitto
    expose:
        - "8883"
        - "9001"
    ports:
        - "8883:8883"
        - "9001:9001"