version: "3.7"
services:
  rabbitmqt:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9890:15672
      - 8888:5672
    hostname: stats
    volumes:
      - ./.volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - type: bind
        source: ./rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
  mongo-local:
    image: mongo:7.0.1
    container_name: mongo-local
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo-local:27017/local --quiet
      interval: 10s
      timeout: 10s
      retries: 7
      start_period: 50s
    env_file:
      - ./.services/mongo/.env
    volumes: 
      - './.volumes/mongo:/data/db'
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express:1.0.0-alpha
    container_name: mongo-express
    depends_on:
      mongo-local:
        condition: service_healthy
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./.services/mongo-express/.env
