version: "3.7"
services:
  rabbitmqt:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9890:15672
      - 8888:5672
    hostname: stats
    volumes:
      - ./.volumes/rabbitmq/data:/var/lib/rabbitmq/mnesia
      - type: bind
        source: ./rabbitmq/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbitmq/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbitmq/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json